# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0002_auto_20170623_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('lunch', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_enroll', to='app_longquan.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='emailsub',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_member_name',
            field=models.CharField(max_length=40),
        ),
    ]
