# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 01:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0003_auto_20170623_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
