# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0005_auto_20170624_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='seminar_topic',
            new_name='seminar_title',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='seminar_text',
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_content',
            field=models.TextField(default=b'\xe9\xbe\x99\xe6\xb3\x89\xe5\xa4\xa7\xe6\x82\xb2\xe5\xaf\xba'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_description',
            field=models.TextField(default=b'to be add', max_length=2000),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_photo',
            field=models.ImageField(default=b'', upload_to=b'seminar/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(default=b'to be added', max_length=2000),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_location',
            field=models.CharField(default=b'\xe9\xbe\x99\xe6\xb3\x89\xe5\xa4\xa7\xe6\x82\xb2\xe5\xaf\xba', max_length=50),
        ),
    ]
