# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 10:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0007_auto_20170624_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='seminar_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=b'\xe9\xbe\x99\xe6\xb3\x89\xe5\xa4\xa7\xe6\x82\xb2\xe5\xaf\xba'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=b'to be add', max_length=2000),
        ),
    ]
