# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0008_auto_20170624_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_enroll', to='app_longquan.Seminar')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
