# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 22:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0009_auto_20170624_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=1000)),
                ('article_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xb6\xe9\x97\xb4')),
                ('article_author', models.CharField(max_length=200, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
                ('article_photo', models.ImageField(upload_to=b'article/')),
                ('article_description', ckeditor_uploader.fields.RichTextUploadingField(default=b'to be add')),
                ('article_content', ckeditor_uploader.fields.RichTextUploadingField(default=b'to be add')),
                ('article_click', models.IntegerField(verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe9\x87\x8f')),
                ('article_top', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\xbd\xae\xe9\xa1\xb6')),
                ('article_published', models.BooleanField(default=True, verbose_name=b'\xe6\xad\xa3\xe5\xbc\x8f\xe5\x8f\x91\xe5\xb8\x83')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=256, verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=256)),
                ('comment_email', models.CharField(max_length=256)),
                ('comment_content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acticle_comment', to='app_longquan.Article')),
                ('comment_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_longquan.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x90\x8d')),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='app_longquan.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='app_longquan.Column'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(blank=True, to='app_longquan.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
    ]
