# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0010_auto_20170625_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='app_longquan.Article'),
        ),
    ]
