# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0012_auto_20170627_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_longquan.Comment'),
        ),
    ]
