# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0016_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_schedule', models.CharField(max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_schedule', to='app_longquan.Activity')),
            ],
        ),
    ]
