# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 19:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0018_activityenroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86\xe5\x86\x85\xe5\xae\xb9\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x97\xa5\xe6\x9c\x9f\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.TextField(default=b'', max_length=2000, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9\xe7\xae\x80\xe4\xbb\x8b\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_location',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'\xe5\x9c\xb0\xe7\x82\xb9\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_photo',
            field=models.ImageField(default=b'', upload_to=b'activities/', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_publisher',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe8\x80\x85\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_source',
            field=models.TextField(default=b'', max_length=2000, verbose_name=b'\xe4\xbf\xa1\xe6\x81\xaf\xe6\x9d\xa5\xe6\xba\x90\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
    ]
