# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0021_auto_20170815_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='app_longquan.Column', verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0\xef\xbc\x88\xe5\xbf\x85\xe9\x80\x89\xef\xbc\x89'),
        ),
    ]
