# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0022_auto_20170815_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventenroll',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventEnroll',
        ),
        migrations.DeleteModel(
            name='EventSchedule',
        ),
    ]
