# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0023_auto_20170816_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=256, verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='app_longquan.ActivityColumn', verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0\xef\xbc\x88\xe5\xbf\x85\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_publisher',
            field=models.CharField(blank=True, default=b'\xe9\xbe\x99\xe6\xb3\x89\xe5\xa4\xa7\xe6\x82\xb2\xe5\xaf\xba', max_length=100, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe8\x80\x85\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
    ]
