# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0025_auto_20170816_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89')),
                ('speaker_role', models.CharField(default=b'', max_length=100, verbose_name=b'\xe8\x81\x8c\xe4\xbd\x8d\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89')),
                ('speaker_photo', models.ImageField(blank=True, default=b'', upload_to=b'speakers/', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89')),
                ('topic_title', models.CharField(default=b'', max_length=100, verbose_name=b'\xe5\xad\xa6\xe6\x9c\xaf\xe4\xba\xa4\xe6\xb5\x81\xe9\xa2\x98\xe7\x9b\xae\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89')),
                ('topic_desc', models.TextField(default=b'', max_length=2000, verbose_name=b'\xe6\xbc\x94\xe8\xae\xb2\xe5\x86\x85\xe5\xae\xb9\xe7\xae\x80\xe4\xbb\x8b\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89')),
                ('topic_content', models.TextField(default=b'', max_length=20000, verbose_name=b'\xe6\xbc\x94\xe8\xae\xb2\xe5\xae\x8c\xe6\x95\xb4\xe5\x86\x85\xe5\xae\xb9\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_speaker', to='app_longquan.Activity')),
            ],
        ),
    ]
