# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0027_auto_20170822_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='activity',
        ),
        migrations.AddField(
            model_name='speaker',
            name='activity',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='activity_speakers', to='app_longquan.Activity'),
        ),
    ]
