# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0028_auto_20170822_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker_role',
            new_name='role',
        ),
    ]
