# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 19:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0029_auto_20170822_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_time',
        ),
        migrations.AddField(
            model_name='article',
            name='article_pubDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xb6\xe9\x97\xb4\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_source',
            field=models.CharField(blank=True, default=b'', max_length=200, verbose_name=b'\xe4\xbf\xa1\xe6\x81\xaf\xe6\x9d\xa5\xe6\xba\x90\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.CharField(max_length=200, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='app_longquan.Column', verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0\xef\xbc\x88\xe5\xbf\x85\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86\xe5\x86\x85\xe5\xae\xb9\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9\xe7\xae\x80\xe4\xbb\x8b\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_photo',
            field=models.ImageField(blank=True, default=b'', upload_to=b'articles/', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=1000, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
    ]
