# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0030_auto_20170824_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_click',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe9\x87\x8f'),
        ),
    ]
