# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0031_auto_20170826_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default=b'', max_length=200, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89')),
                ('text', models.TextField(blank=True, default=b'', max_length=20000, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89')),
                ('picture', models.ImageField(blank=True, default=b'', upload_to=b'activities/', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89')),
                ('pub_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
