# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0033_auto_20170826_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_publisher',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe8\x80\x85\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='topic',
            field=models.CharField(default=b'', max_length=200, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98\xef\xbc\x88\xe5\xbf\x85\xe5\xa1\xab\xef\xbc\x89'),
        ),
    ]
