# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 18:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_longquan', '0034_auto_20170826_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9\xef\xbc\x88\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x89'),
        ),
    ]
